### ISSUE TITLE
Increase readability/modularity

### ISSUE THREAD

**Issue by chrisK824** [Kelvin-Kwashie/Space-Invaders#2]
Must have: 

- Comments and docstrings: as already stated in first project, try to comment your code, so that anyone else that is reading (or even future you reading that back) can understand easier what is doing what and why. This is a must have when you are working with others that need to read and understand your code  ( just like me :p )

Nice to have:

- Consider splitting pieces of code to reduce complexity. e.g classes can be separate modules so that one can focus on one element at a time when reading, modifying etc

**Comment by Kelvin-Kwashie** [comment]
Sure
