### ISSUE TITLE
Enhance documentation

### ISSUE THREAD

**Issue by chrisK824** [Kelvin-Kwashie/Space-Invaders#3]
Documentation must be always sufficient in work that you share. In this first try you have added a readme file with the how-to-play guide. This is a Usage documentation. However, you need to expand that documentation to make it more complete in more levels:

1. Developers documentation: This would include (at least high level or even thorough) documentation of the logic of the code, the approaches followed, whys and hows etc. In some cases where you deliver a piece of software to a third party (company, individual clients etc), this documentation must be exhaustive, so that all is understood and replicatable from the other side. In any case though, as already mentioned earlier, the developer's documentation is enhanced with comments and docstrings in the code itself. That is not a replacement of a focused documentation, but it's a minimum level of documentation in cases where the project is not crucial or there is just not enough time for it.

2. Installation and execution documentation: Describes how to install the software and execute it. In your case and python in general there are couple approaches for dependencies and shipment. Search around for the usage of `pip` and/or `poetry` . Personally I prefer `pip` as it is simpler, especially for that kind of simple projects, but `poetry` is powerful and a rising star on that matter. After your research try to include a `requirements.txt` with dependencies that your code requires, along with installation and execution instructions. Like, where this software has been tested and working, what platform/os, which python runtime, how to run etc

**Comment by Kelvin-Kwashie** [comment]
Well understood

**Comment by Kelvin-Kwashie** [comment]
It has been solved
