### ISSUE TITLE
Class usage explanation

### ISSUE THREAD

**Issue by chrisK824** [Kelvin-Kwashie/Space-Invaders#4]
Since you seem to have dived into Classes and Object Oriented Programming (OOP) approach, I would like to see your understanding of the concepts so far. It is crucial to understand in depth what the code does and why it behaves the way it behaves.

So, for this task, I would like a small essay (it can be part of the Developers documentation in this repo really) where you explain:
- How you selected the classes to implement?
- How you used inheritance of classes and why?
- How did you use override of inherited methods and why? Could this be done in a cleaner way?

**Comment by Kelvin-Kwashie** [comment]
I will get that done as soon as possible
